version: 1.0.0

sources:
  - name: medadvantage
    schema: public
    tables:
      - name: members
      - name: medical_claims
      - name: pharmacy_claims
      - name: icd_to_hcc
      - name: ndc_to_rxhcc